languages: cpp
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            - libblas-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"
    - export CC=/usr/bin/gcc-8

script: 
  - cd tests
  - make travis
  - ./blackcat_tests
  - cd ../examples/mnist_test/ 
  - make travis
  - ./mnist_test_exec
  - cd ../mnist_test_recurrent
  - make travis
  - ./mnist_test_exec 
